coverage:
  status:
    project:
      default:
        target: auto
      graphql-no-alias:
        target: auto
        flags:
          - graphql-no-alias

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flags:
  graphql-no-alias:
    paths:
      - packages/graphql-no-alias/
    carryforward: true
