coverage:
  status:
    project:
      default:
        target: auto
      dumba:
        target: auto
        flags:
          - dumba

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flags:
  dumba:
    paths:
      - packages/dumba/
    carryforward: true
